config/routes.rb
Rails.application.routes.draw do
  root 'landings#index'

  # Authentication routes
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :admin, path: 'admin',
                     as: 'admin',
                     only: [:index, :destroy]

  resources :users, path: 'profile',
                    as: 'profile',
                    param: :username,
                    only: [:edit, :update]

  # Public routes
  get '/:url_id', to: 'url#redirect_user', as: 'redirect'
  get '/s/:url_id', to: 'url#show', as: 'settings'
  post '/', to: 'url#generate', as: 'generate'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord
  # TODO: IT IS NOT QUIET GOOD!
  validates :url, presence: true,
                  format: { with: /\A(http|https):\/\/(\S+)\z/ }
  validates :url_id, presence: true,
                     uniqueness: { case_sensitive: true }
  validates :status, inclusion: [true, false]
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  # TODO: Write regex for email and username
  validates :username, presence: true
  # TODO: Discus this password validation
  validates :password, length: { minimum: 8 }, allow_nil: true
  validates :role, presence: true, 
                   format: { with: /\AADMIN\z/ }
  validates :email, presence: false
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authorize

  # Get all URL from database
  def index
    @url = Url.all
  end

  # Delete query from database with :delete method
  def destroy
    url = Url.find(params[:id])

    # If it is successful return a success message with flash
    # If not return error message. Sysadmin should check error.
    # TODO: Write I18n for 19 and 22.
    if url.destroy
      flash[:success] = t 'dashboard.successfully_deleted'
    else
      flash[:danger] = t 'error.check_logs'
    end
    redirect_to admin_index_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_path unless current_user
  end

  def logged_in?
    !current_user.nil?
  end
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  def index; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :authorize, only: [:destroy]

  def new
    # TODO: This is not good way to use.
    #   We need to add something there..
    if logged_in?
      redirect_to root_path
    else
      render 'sessions/new'
    end
  end

  def create
    user = User.find_by(username: params[:username])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = t 'session.logged_in_ok'
      redirect_to admin_index_path
    else
      flash[:danger] = t 'error.invalid_combination'
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = t 'session.logged_out_ok'
    redirect_to root_path
  end
end

app/controllers/url_controller.rb
class UrlController < ApplicationController
  def index; end

  def show
    @url = Url.find_by url_id: params[:url_id]

    unless @url
      flash[:danger] = t 'error.short_link_not_found'
      render 'landings/index'
    end
  end

  def redirect_user
    @url = Url.find_by url_id: params[:url_id]

    if @url
      @url.update click: @url.click + 1
      redirect_to @url.url
    else
      flash[:danger] = t 'error.short_link_not_found'
      render 'landings/index'
    end
  end

  def generate
    @url = Url.new(params.require(:url).permit(:url, :status))
    @url.url_id = generate_id

    if @url.save
      redirect_to settings_path @url.url_id
    else
      flash[:danger] = t 'error.something_went_wrong'
      render 'landings/index'
    end
  end

  private

  def generate_id
    alphabet = Array('A'..'Z') + Array('a'..'z')
    numbers = Array(0..9)
    Array.new(6) { (alphabet + numbers).sample }.join
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize

  def edit;
    @user = User.find_by username: params[:username]
  end
  
  def update
    user = User.find_by username: params[:username]
    if user.update(params.require(:user).permit(:username, :email, :password, :password_confirmation))
      redirect_to root_path
    else
      render 'users/edit'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/index.html.erb
<%= provide(:title, 'Dashboard') %>

<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

<div class="row">
  <div class="col-12 col-md-3">
    <h2><%= t 'dashboard.sidebar' %></h2>
    <div class="list-group">
      <%= link_to t('dashboard.analytics'),
                  admin_index_path,
                  class: 'list-group-item list-group-item-action' %>
      <%= link_to t('dashboard.latest_url'),
                  admin_index_path,
                  class: 'list-group-item list-group-item-action' %>
    </div>
  </div>
  <div class="col-12 col-md-9">
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th><%= t 'dashboard.table.original_url' %></th>
            <th><%= t 'dashboard.table.generated_url' %></th>
            <th><%= t 'global.status' %></th>
            <th><%= t 'dashboard.table.created_at' %></th>
            <th><%= t 'dashboard.table.action' %></th>
          </tr>
        </thead>
        <tbody>
        <% @url.each do |url| %>
          <tr>
            <td><%= url.url %></td>
            <td><%= url.url_id %></td>
            <td><% if url.status %><%= t 'global.private' %><% else %><%= t 'global.public' %><% end %></td>
            <td>
              <time datetime="<%= url.created_at %>">
                <%= url.created_at.strftime("%A, %b %d, %Y, %I:%M %p") %>
              </time>
            </td>
            <td><%= link_to t('global.delete'), admin_path(url),
                                      method: :delete,
                                      data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/landings/index.html.erb
<%= provide(:title, t('landing.title')) %>

<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

<h1 class="text-center" style="padding-top: 80px;">URL-Shortner</h1>

<div class="row h-100 justify-content-center align-items-center">
  <div class="col-12 col-md-6">
    <%= form_for :url, url: generate_path, local: true do |form| %>
      <div class="input-group">
        <div class="input-group mb-3">
          <%= form.url_field :url, class: 'form-control', required: true, autofocus: true, placeholder: t('landing.enter_an_url'), 'aria-label': t('landing.enter_an_url'), 'aria-describedby': t('landing.enter_an_url') %>
          <div class="input-group-append">
            <%= form.submit t('landing.generate'), class: 'btn btn-outline-primary', 'aria-label': t('landing.generate'), 'aria-describedby': t('landing.generate')  %>
          </div>
        </div>
      </div>
      <div class="form-check text-right">
        <%= form.check_box :status %> <%= t('landing.is_private') %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content="yet-another URL shorter for everyone."/>
    <meta name="author" content="Yedukondala Reddy"/>

    <title><%= yield :title %> | URL-Shortner</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'hdata-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <nav class="navbar navbar-expand-md navbar-light bg-light mb-4">
        <div class="container">
          <%= link_to 'URL-Shortner', root_path, class: 'navbar-brand' %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto"></ul>
            <ul class="navbar-nav">
              <% unless current_user %>
                <li class="nav-item">
                  <%= link_to t('navbar.login'), login_path, class: 'nav-link' %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to t('navbar.dashboard'), admin_index_path, class: 'nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to t('navbar.settings'), edit_profile_path(current_user.username), class: 'nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to t('navbar.logout'), logout_path, class: 'nav-link' %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </div>

    <div class="container h-100">
      <%= yield %>
    </div>

    <footer class="modal-footer bg-light">
      <div class="container">
        <span class="text-muted">Copyright <%= Time.current.year %>, <a href="https://github.com/yrmallu/url-shortner">URL-Shortner</a></span>
      </div>
    </footer>

    <% console if Rails.env.development? %>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.slim.min.js" integrity="sha256-3edrmyuQ0w65f8gfBsqowzjJe2iM6n0nKciPUp8y+7E=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.1/umd/popper.min.js" integrity="sha256-AoNQZpaRmemSTxMy9xcqXX5VLwI6IMPYugO7bFHOW+U=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha256-5+02zu5UULQkO7w1GIr6vftCgMfFdZcAHeDtFnKZsBs=" crossorigin="anonymous"></script>
  </body>
</html>

app/views/url/show.html.erb
<%= provide(:title, @url.url ) %>
<br>
<p><strong><%= t 'show.original_url' %>:</strong> <%= @url.url %> </p>
<p><strong><%= t 'show.shortened_link' %>:</strong> <%= link_to @url.url_id, redirect_path %> </p>
<p><strong><%= t 'show.clicked' %> :</strong> <%= @url.click %> </p>
<p><strong><%= t 'global.status' %>:</strong> <% if @url.status %><%= t 'global.private' %><% else %><%= t 'global.public' %><% end %> </p>

app/views/users/edit.html.erb
<%= provide(:title, 'Edit') %>

<h1>Edit profile</h1>
<div class="d-flex justify-content-center">
  <%= form_with model: @user, url: profile_path, method: :put do |form| %>
    <%= t 'global.email' %>
    <%= form.email_field :email, class: 'form-control' %>
    <%= t 'global.username' %>
    <%= form.text_field :username, class: 'form-control' %>
    <%= t 'global.password' %>
    <%= form.password_field :password, class: 'form-control' %>
    <%= t 'global.password_confirmation' %>
    <%= form.password_field :password_confirmation, class: 'form-control' %> <br>
    <%= form.submit "Submit", class: 'btn btn-warning' %>
  <% end %>
</div>